### ISSUE TITLE
Cannot Find Source Code

### ISSUE THREAD

**Issue by Chandler-Kluser** [X-death25/MD-Dumper#4]
Greetings,

I would like to thank you so much for opening your project for the Open Source Community!

I am trying to DIY your board here to make my own cartridges, but I cannot find the STM32 Source Code and the Board Schematic (neither the bill of materials).

I would appreciate so much if you could share it

Thanks in advance!

**Comment by X-death25** [comment]
Hi,
Yes of course !
i have just released the ARM source code , Gerber files and Kicad PCB files.
Feel free to ask here or in the discord if you need some help , or if something is broken.
Greeetings from France

**Comment by Chandler-Kluser** [comment]
Thanks a lot, dear friend!!
