### ISSUE TITLE
.text starting at 0x08004000?

### ISSUE THREAD

**Issue by Chandler-Kluser** [X-death25/MD-Dumper#5]
Building Firmware from source using OPENCM3_DIR to the latest build of [libopencm3](https://github.com/libopencm3/libopencm3) with this build of `arm-none-eabi-gcc`:

```
arm-none-eabi-gcc (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 12.2.1 20221205
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I was able to fully compile the MD Dumper firmware, but something caught me before I flash into my blackpill:

![image](https://github.com/X-death25/MD-Dumper/assets/29960960/0448a8e4-7e87-496d-befb-080c1e06fbda)

Notice that the .text starts at `0x08004000` instead of `0x08000000`, can someone confirm that?

Thanks in advance!

**Comment by X-death25** [comment]
Hi,
just read the code
stm32f401.ld line 26
rom (rx) : ORIGIN =  0x08004000, LENGTH = 512K

**Comment by Chandler-Kluser** [comment]
I truly read that, but I though it was some kind of mistyping. Never mind
